#!/usr/bin/env bash
#printing Best School 10 times, good luck and bad luck
i=1

while [ "$i" -le 8 ]
do
      echo "Best School"

if [ "$i" -eq 3 ]
then
   echo "bad luck"
elif [ "$i" -eq 7 ]
then
    echo "good luck"
else
    echo "Best School"
fi

    ((i++))
done
