#!/usr/bin/env bash
#creating a file that contains this process pid

echo "pgrep /var/run/myscript.pid"> /var/run/myscript.pid

trap "I hate the kill command" SIGTERM
trap "Y U no love me?!" SIGINT

trap rm /var/run/myscript.pid SIGQUIT

while :
do 
echo "To infinity and beyond"
done
