#!/usr/bin/env bash
#managing another file

command=$1

if [ -z "$command" ]
then
echo "Usage: manage_my_process {start|stop|restart}"
fi

if [ "$command" == start ]
then
   bash ./manage_my_process &
   echo "$!"> /var/run/my_process.pid
   echo "manage_my_process started"
fi


if [ "$command" == stop ]
then
    echo "manage_my_process stopped"	
    pkill -f manage_my_process
    rm /var/run/my_process.pid
fi


if [ "$command" == restart ]
then
    echo "manage_my_process restarted"	
    pkill -f manage_my_process
    rm /var/run/my_process.pid
    bash ./manage_my_process
    echo "$!"> /var/run/my_process.pid
fi


